### ISSUE TITLE
Convert Auto Value to be jsonafiable

### ISSUE THREAD

**Issue by bwillard** [google/data-portability#4]

**Comment by holachuy** [comment]
FYI https://github.com/artem-zinnatullin/AutoJackson

**Comment by rtannenbaum** [comment]
I have an old gist I made of doing this the Jackson @JsonCreator way: https://gist.github.com/rtannenbaum/9922330

**Comment by holachuy** [comment]
Depends on new transfer types, let's revisit this when we move over to gradle and the new SPI/APIs

**Comment by holachuy** [comment]
Closing issue as new SPI types will not use AutoValue
